name: Build
on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop
    tags:
      - '*'
jobs:
  Build:
    name: 'Build and Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node_version:
          - 20
          - 22
          - 24
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Use Node.js ${{ matrix.node_version }}'
        uses: actions/setup-node@v6
        with:
          node-version: '${{ matrix.node_version }}'
      - name: npm build and test
        run: |
          npm ci
          npm run build
          npm test

  Container:
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Write version vars
        id: version-vars
        run: |
          BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          BRANCH=${GITHUB_REF_NAME#v}
          APP_VERSION=$(jq -r ".version" package.json)
          echo Version: $APP_VERSION
          echo "VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Build Container Image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            cloudtooling/k6s:next
            cloudtooling/k6s:${{github.run_id }}
            cloudtooling/k6s:${{env.APP_VERSION}}_rc
          build-args: |
            BUILD_DATE=${{env.BUILD_DATE}}
            APP_VERSION=${{env.APP_VERSION}}

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        if: github.ref == 'refs/heads/develop'

      - name: Deploy Container Image
        id: push-to-dockerhub-release
        run: |
          docker push cloudtooling/k6s:next
          docker push cloudtooling/k6s:${{env.APP_VERSION}}_rc
        if: github.ref == 'refs/heads/develop'

  Build-results:
    name: Build results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - Build
      - Container
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{

               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
            }}
